apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jenkins
  labels:
    app: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - image: breqwatrdemo/appapi
        imagePullPolicy: Always
        name: appapi

---

apiVersion: v1
kind: Service
metadata:
  namespace: jenkins
  labels:
  labels:
    app: app
  name: app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: app
  type: LoadBalancer
