---
controller:
  serviceType: LoadBalancer
  adminUser: "breqwatr"
  installPlugins:
    - kubernetes:1.29.4
    - workflow-aggregator:2.6
    - git:4.7.1
    - configuration-as-code:1.51
    - blueocean:1.24.7
    - kubernetes-cd:1.0.0
    - docker-workflow:1.26
    - docker-plugin:1.2.2
    - github:1.33.1

agent:
  volumes:
  - type: HostPath
    hostPath: /var/run/docker.sock
    mountPath: /var/run/docker.sock
